# Generated by Django 5.0.4 on 2024-10-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedios',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=30)),
                ('Descripcion', models.TextField(max_length=150)),
                ('Precio', models.FloatField()),
                ('Imagen', models.ImageField(null=True, upload_to='Remedios')),
            ],
        ),
    ]
